import type { NextPage } from 'next';
import Head from 'next/head';
import PokemonCard from '../components/pokemonCard/card';
import Header from '../components/header/header';
import usePokemonData from '../hooks/usePokemonData';
import { getImageUrl } from '../services/getImageUrl';
import styles from '../styles/Home.module.css';
import Pagination from '../components/pagination/pagination';
import { useState } from 'react';
import CardShimmer from '../components/cardShimmer/shimmer';
import useDebounce from '../hooks/useDebounce';
import Search from '../components/search/search';
import ShimmerGroup from '../components/cardShimmer/shimmerGroup';
const Home: NextPage = () => {
  const [offset, setOffset] = useState(0);
  const [limit, setLimit] = useState(20);
  const [search, setSearch] = useState('');
  const debouncedSearch = useDebounce(search, 500);
  const { loading, error, data } = usePokemonData({
    offset,
    limit,
    search: debouncedSearch,
  });
  console.log(data);
  return (
    <div className="body-content">
      <Head>
        <title>Pokemon app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div className="flex flex-space-between w-100 flex-align-center">
          <Search
            value={search}
            onChange={(input) => {
              setSearch(input);
              setOffset(0);
            }}
          />
          <select>
            <option></option>
            <option></option>
            <option></option>
          </select>
          <Pagination
            onClickPrevious={() => {
              setOffset(offset - limit);
            }}
            onClickNext={() => {
              setOffset(offset + limit);
            }}
            showPrevious={offset !== 0}
            limit={limit}
            setLimit={(input) => {
              setLimit(input);
              setOffset(0);
            }}
          />
        </div>
        <div className={styles.container}>
          {loading && (
            <ShimmerGroup count={10}/>
          )}
          {data
            ? data.pokemon_v2_pokemon.map(
                (item: {
                  name: string;
                  weight: number;
                  height: number;
                  id: number;
                  pokemon_v2_pokemonabilities: any;
                }) => (
                  <PokemonCard
                    id={item.id}
                    key={item.id}
                    name={item.name}
                    weight={item.weight}
                    height={item.height}
                    imgUrl={getImageUrl(item.id)}
                    abilities={item.pokemon_v2_pokemonabilities.map(
                      (ability: any, index: number) => {
                        return ability.pokemon_v2_ability.name;
                      },
                    )}
                  />
                ),
              )
            : null}
        </div>
        <Pagination
          onClickPrevious={() => {
            setOffset(offset - limit);
          }}
          onClickNext={() => {
            setOffset(offset + limit);
          }}
          showPrevious={offset !== 0}
          limit={limit}
          setLimit={setLimit}
        />
      </main>
    </div>
  );
};

export default Home;
